function CutterOption_SelectAndDelete(self)

self.StoreUndo('Select and Delete');
names = self.getClusterNames;
clustersToDelete = listdlg(...
    'ListString', names, ...
    'Name', 'Delete clusters', ...
    'PromptString', 'Select clusters to delete...', ...
    'OKString', 'DONE', 'CancelString', 'Cancel', ...
    'InitialValue', []);

if ~isempty(clustersToDelete)
    self.Clusters(clustersToDelete) = [];
    self.ReGo();
end