function ClusterFunc_00_ShowInfo(self)

S = {self.name, ...
    sprintf('@%s', class(self)), ...
    sprintf('%d spikes', self.nSpikes()), '', ...
    };
for iL = 1:self.nLimits
    S = cat(2, S, ...
        sprintf('Limited on < %s X %s >', self.featuresX{iL}.name, self.featuresY{iL}.name));
end
msgbox(S, self.name);
end